### ISSUE TITLE
PID Names

### ISSUE THREAD

**Issue by VinceW31** [peternixon/MG-EV-OBD-PID#1]
Great work! Just uploaded those extended PIDs of yours to Torque Pro and most seem to work. However, when you try to create Virtual PIDs that add or subtract two of your extended PIDs I've discovered the Vitual PID will not work because the equation editor doesn't like your filenames with the leading dots. I wanted to subtract the "..eZS_CellMinVolts" from the "..eZS_CellMaxVolts" value to show the Balance Error, I got it to work after creating two new PIDs based on yours using simple filenames eg ezs_cellmaxv.
Suggest renaming your PIDs if you want to use them to create new virtual PIDs from them.

**Comment by peternixon** [comment]
In-fact the file you've used is a historical one that I received part-way through development from the Thai ZS EV user group. My PID list is called "MG ZS EV.csv" (as you can see in the instructions) and it does not have any leading dots. It also already contains a Virtual PID called "MG BMS Voltage Delta" which should give you the info you are looking for :)
